const chars = [
  {
    id: "banjo_and_kazooie",
    title: "Banjo & Kazooie",
    thumbnailURL:
      "https://ultimateframedata.com/characterart/banjo_and_kazooie.jpg",
    ufPage: "https://ultimateframedata.com/banjo_and_kazooie.php",
  },
  {
    id: "bayonetta",
    title: "Bayonetta",
    thumbnailURL: "https://ultimateframedata.com/characterart/bayonetta.jpg",
    ufPage: "https://ultimateframedata.com/bayonetta.php",
  },
  {
    id: "bowser",
    title: "Bowser",
    thumbnailURL: "https://ultimateframedata.com/characterart/bowser.jpg",
    ufPage: "https://ultimateframedata.com/bowser.php",
  },
  {
    id: "bowser_jr",
    title: "Bowser Jr.",
    thumbnailURL: "https://ultimateframedata.com/characterart/bowser_jr.jpg",
    ufPage: "https://ultimateframedata.com/bowser_jr.php",
  },
  {
    id: "byleth",
    title: "Byleth",
    thumbnailURL: "https://ultimateframedata.com/characterart/byleth.jpg",
    ufPage: "https://ultimateframedata.com/byleth.php",
  },
  {
    id: "captain_falcon",
    title: "Captain Falcon",
    thumbnailURL:
      "https://ultimateframedata.com/characterart/captain_falcon.jpg",
    ufPage: "https://ultimateframedata.com/captain_falcon.php",
  },
  {
    id: "chrom",
    title: "Chrom",
    thumbnailURL: "https://ultimateframedata.com/characterart/chrom.jpg",
    ufPage: "https://ultimateframedata.com/chrom.php",
  },
  {
    id: "cloud",
    title: "Cloud",
    thumbnailURL: "https://ultimateframedata.com/characterart/cloud.jpg",
    ufPage: "https://ultimateframedata.com/cloud.php",
  },
  {
    id: "corrin",
    title: "Corrin",
    thumbnailURL: "https://ultimateframedata.com/characterart/corrin.jpg",
    ufPage: "https://ultimateframedata.com/corrin.php",
  },
  {
    id: "daisy",
    title: "Daisy",
    thumbnailURL: "https://ultimateframedata.com/characterart/daisy.jpg",
    ufPage: "https://ultimateframedata.com/daisy.php",
  },
  {
    id: "dark_pit",
    title: "Dark Pit",
    thumbnailURL: "https://ultimateframedata.com/characterart/dark_pit.jpg",
    ufPage: "https://ultimateframedata.com/dark_pit.php",
  },
  {
    id: "dark_samus",
    title: "Dark Samus",
    thumbnailURL: "https://ultimateframedata.com/characterart/dark_samus.jpg",
    ufPage: "https://ultimateframedata.com/dark_samus.php",
  },
  {
    id: "diddy_kong",
    title: "Diddy Kong",
    thumbnailURL: "https://ultimateframedata.com/characterart/diddy_kong.jpg",
    ufPage: "https://ultimateframedata.com/diddy_kong.php",
  },
  {
    id: "donkey_kong",
    title: "Donkey Kong",
    thumbnailURL: "https://ultimateframedata.com/characterart/donkey_kong.jpg",
    ufPage: "https://ultimateframedata.com/donkey_kong.php",
  },
  {
    id: "dr_mario",
    title: "Dr. Mario",
    thumbnailURL: "https://ultimateframedata.com/characterart/dr_mario.jpg",
    ufPage: "https://ultimateframedata.com/dr_mario.php",
  },
  {
    id: "duck_hunt",
    title: "Duck Hunt",
    thumbnailURL: "https://ultimateframedata.com/characterart/duck_hunt.jpg",
    ufPage: "https://ultimateframedata.com/duck_hunt.php",
  },
  {
    id: "falco",
    title: "Falco",
    thumbnailURL: "https://ultimateframedata.com/characterart/falco.jpg",
    ufPage: "https://ultimateframedata.com/falco.php",
  },
  {
    id: "fox",
    title: "Fox",
    thumbnailURL: "https://ultimateframedata.com/characterart/fox.jpg",
    ufPage: "https://ultimateframedata.com/fox.php",
  },
  {
    id: "ganondorf",
    title: "Ganondorf",
    thumbnailURL: "https://ultimateframedata.com/characterart/ganondorf.jpg",
    ufPage: "https://ultimateframedata.com/ganondorf.php",
  },
  {
    id: "greninja",
    title: "Greninja",
    thumbnailURL: "https://ultimateframedata.com/characterart/greninja.jpg",
    ufPage: "https://ultimateframedata.com/greninja.php",
  },
  {
    id: "hero",
    title: "Hero",
    thumbnailURL: "https://ultimateframedata.com/characterart/hero.jpg",
    ufPage: "https://ultimateframedata.com/hero.php",
  },
  {
    id: "ice_climbers",
    title: "Ice Climbers",
    thumbnailURL: "https://ultimateframedata.com/characterart/ice_climbers.jpg",
    ufPage: "https://ultimateframedata.com/ice_climbers.php",
  },
  {
    id: "ike",
    title: "Ike",
    thumbnailURL: "https://ultimateframedata.com/characterart/ike.jpg",
    ufPage: "https://ultimateframedata.com/ike.php",
  },
  {
    id: "incineroar",
    title: "Incineroar",
    thumbnailURL: "https://ultimateframedata.com/characterart/incineroar.jpg",
    ufPage: "https://ultimateframedata.com/incineroar.php",
  },
  {
    id: "inkling",
    title: "Inkling",
    thumbnailURL: "https://ultimateframedata.com/characterart/inkling.jpg",
    ufPage: "https://ultimateframedata.com/inkling.php",
  },
  {
    id: "isabelle",
    title: "Isabelle",
    thumbnailURL: "https://ultimateframedata.com/characterart/isabelle.jpg",
    ufPage: "https://ultimateframedata.com/isabelle.php",
  },
  {
    id: "jigglypuff",
    title: "Jigglypuff",
    thumbnailURL: "https://ultimateframedata.com/characterart/jigglypuff.jpg",
    ufPage: "https://ultimateframedata.com/jigglypuff.php",
  },
  {
    id: "joker",
    title: "Joker",
    thumbnailURL: "https://ultimateframedata.com/characterart/joker.jpg",
    ufPage: "https://ultimateframedata.com/joker.php",
  },
  {
    id: "ken",
    title: "Ken",
    thumbnailURL: "https://ultimateframedata.com/characterart/ken.jpg",
    ufPage: "https://ultimateframedata.com/ken.php",
  },
  {
    id: "king_dedede",
    title: "King Dedede",
    thumbnailURL: "https://ultimateframedata.com/characterart/king_dedede.jpg",
    ufPage: "https://ultimateframedata.com/king_dedede.php",
  },
  {
    id: "king_k_rool",
    title: "King K. Rool",
    thumbnailURL: "https://ultimateframedata.com/characterart/king_k_rool.jpg",
    ufPage: "https://ultimateframedata.com/king_k_rool.php",
  },
  {
    id: "kirby",
    title: "Kirby",
    thumbnailURL: "https://ultimateframedata.com/characterart/kirby.jpg",
    ufPage: "https://ultimateframedata.com/kirby.php",
  },
  {
    id: "link",
    title: "Link",
    thumbnailURL: "https://ultimateframedata.com/characterart/link.jpg",
    ufPage: "https://ultimateframedata.com/link.php",
  },
  {
    id: "little_mac",
    title: "Little Mac",
    thumbnailURL: "https://ultimateframedata.com/characterart/little_mac.jpg",
    ufPage: "https://ultimateframedata.com/little_mac.php",
  },
  {
    id: "lucario",
    title: "Lucario",
    thumbnailURL: "https://ultimateframedata.com/characterart/lucario.jpg",
    ufPage: "https://ultimateframedata.com/lucario.php",
  },
  {
    id: "lucas",
    title: "Lucas",
    thumbnailURL: "https://ultimateframedata.com/characterart/lucas.jpg",
    ufPage: "https://ultimateframedata.com/lucas.php",
  },
  {
    id: "lucina",
    title: "Lucina",
    thumbnailURL: "https://ultimateframedata.com/characterart/lucina.jpg",
    ufPage: "https://ultimateframedata.com/lucina.php",
  },
  {
    id: "luigi",
    title: "Luigi",
    thumbnailURL: "https://ultimateframedata.com/characterart/luigi.jpg",
    ufPage: "https://ultimateframedata.com/luigi.php",
  },
  {
    id: "mario",
    title: "Mario",
    thumbnailURL: "https://ultimateframedata.com/characterart/mario.jpg",
    ufPage: "https://ultimateframedata.com/mario.php",
  },
  {
    id: "marth",
    title: "Marth",
    thumbnailURL: "https://ultimateframedata.com/characterart/marth.jpg",
    ufPage: "https://ultimateframedata.com/marth.php",
  },
  {
    id: "mega_man",
    title: "Mega Man",
    thumbnailURL: "https://ultimateframedata.com/characterart/mega_man.jpg",
    ufPage: "https://ultimateframedata.com/mega_man.php",
  },
  {
    id: "meta_knight",
    title: "Meta Knight",
    thumbnailURL: "https://ultimateframedata.com/characterart/meta_knight.jpg",
    ufPage: "https://ultimateframedata.com/meta_knight.php",
  },
  {
    id: "mewtwo",
    title: "Mewtwo",
    thumbnailURL: "https://ultimateframedata.com/characterart/mewtwo.jpg",
    ufPage: "https://ultimateframedata.com/mewtwo.php",
  },
  {
    id: "mii_brawler",
    title: "Mii Brawler",
    thumbnailURL: "https://ultimateframedata.com/characterart/mii_brawler.jpg",
    ufPage: "https://ultimateframedata.com/mii_brawler.php",
  },
  {
    id: "mii_gunner",
    title: "Mii Gunner",
    thumbnailURL: "https://ultimateframedata.com/characterart/mii_gunner.jpg",
    ufPage: "https://ultimateframedata.com/mii_gunner.php",
  },
  {
    id: "mii_swordfighter",
    title: "Mii Swordfighter",
    thumbnailURL:
      "https://ultimateframedata.com/characterart/mii_swordfighter.jpg",
    ufPage: "https://ultimateframedata.com/mii_swordfighter.php",
  },
  {
    id: "minmin",
    title: "Min Min",
    thumbnailURL: "https://ultimateframedata.com/characterart/minmin.jpg",
    ufPage: "https://ultimateframedata.com/minmin.php",
  },
  {
    id: "mr_game_and_watch",
    title: "Mr. Game & Watch",
    thumbnailURL:
      "https://ultimateframedata.com/characterart/mr_game_and_watch.jpg",
    ufPage: "https://ultimateframedata.com/mr_game_and_watch.php",
  },
  {
    id: "ness",
    title: "Ness",
    thumbnailURL: "https://ultimateframedata.com/characterart/ness.jpg",
    ufPage: "https://ultimateframedata.com/ness.php",
  },
  {
    id: "olimar",
    title: "Olimar",
    thumbnailURL: "https://ultimateframedata.com/characterart/olimar.jpg",
    ufPage: "https://ultimateframedata.com/olimar.php",
  },
  {
    id: "pac_man",
    title: "Pac Man",
    thumbnailURL: "https://ultimateframedata.com/characterart/pac_man.jpg",
    ufPage: "https://ultimateframedata.com/pac_man.php",
  },
  {
    id: "palutena",
    title: "Palutena",
    thumbnailURL: "https://ultimateframedata.com/characterart/palutena.jpg",
    ufPage: "https://ultimateframedata.com/palutena.php",
  },
  {
    id: "peach",
    title: "Peach",
    thumbnailURL: "https://ultimateframedata.com/characterart/peach.jpg",
    ufPage: "https://ultimateframedata.com/peach.php",
  },
  {
    id: "pichu",
    title: "Pichu",
    thumbnailURL: "https://ultimateframedata.com/characterart/pichu.jpg",
    ufPage: "https://ultimateframedata.com/pichu.php",
  },
  {
    id: "pikachu",
    title: "Pikachu",
    thumbnailURL: "https://ultimateframedata.com/characterart/pikachu.jpg",
    ufPage: "https://ultimateframedata.com/pikachu.php",
  },
  {
    id: "piranha_plant",
    title: "Piranha Plant",
    thumbnailURL:
      "https://ultimateframedata.com/characterart/piranha_plant.jpg",
    ufPage: "https://ultimateframedata.com/piranha_plant.php",
  },
  {
    id: "pit",
    title: "Pit",
    thumbnailURL: "https://ultimateframedata.com/characterart/pit.jpg",
    ufPage: "https://ultimateframedata.com/pit.php",
  },
  {
    id: "pt_squirtle",
    title: "Squirtle",
    thumbnailURL: "https://ultimateframedata.com/characterart/pt_squirtle.jpg",
    ufPage: "https://ultimateframedata.com/pt_squirtle.php",
  },
  {
    id: "pt_ivysaur",
    title: "Ivysaur",
    thumbnailURL: "https://ultimateframedata.com/characterart/pt_ivysaur.jpg",
    ufPage: "https://ultimateframedata.com/pt_ivysaur.php",
  },
  {
    id: "pt_charizard",
    title: "Charizard",
    thumbnailURL: "https://ultimateframedata.com/characterart/pt_charizard.jpg",
    ufPage: "https://ultimateframedata.com/pt_charizard.php",
  },
  {
    id: "richter",
    title: "Richter",
    thumbnailURL: "https://ultimateframedata.com/characterart/richter.jpg",
    ufPage: "https://ultimateframedata.com/richter.php",
  },
  {
    id: "ridley",
    title: "Ridley",
    thumbnailURL: "https://ultimateframedata.com/characterart/ridley.jpg",
    ufPage: "https://ultimateframedata.com/ridley.php",
  },
  {
    id: "rob",
    title: "R.O.B.",
    thumbnailURL: "https://ultimateframedata.com/characterart/rob.jpg",
    ufPage: "https://ultimateframedata.com/rob.php",
  },
  {
    id: "robin",
    title: "Robin",
    thumbnailURL: "https://ultimateframedata.com/characterart/robin.jpg",
    ufPage: "https://ultimateframedata.com/robin.php",
  },
  {
    id: "rosalina_and_luma",
    title: "Rosalina and Luma",
    thumbnailURL:
      "https://ultimateframedata.com/characterart/rosalina_and_luma.jpg",
    ufPage: "https://ultimateframedata.com/rosalina_and_luma.php",
  },
  {
    id: "roy",
    title: "Roy",
    thumbnailURL: "https://ultimateframedata.com/characterart/roy.jpg",
    ufPage: "https://ultimateframedata.com/roy.php",
  },
  {
    id: "ryu",
    title: "Ryu",
    thumbnailURL: "https://ultimateframedata.com/characterart/ryu.jpg",
    ufPage: "https://ultimateframedata.com/ryu.php",
  },
  {
    id: "samus",
    title: "Samus",
    thumbnailURL: "https://ultimateframedata.com/characterart/samus.jpg",
    ufPage: "https://ultimateframedata.com/samus.php",
  },
  {
    id: "sheik",
    title: "Sheik",
    thumbnailURL: "https://ultimateframedata.com/characterart/sheik.jpg",
    ufPage: "https://ultimateframedata.com/sheik.php",
  },
  {
    id: "shulk",
    title: "Shulk",
    thumbnailURL: "https://ultimateframedata.com/characterart/shulk.jpg",
    ufPage: "https://ultimateframedata.com/shulk.php",
  },
  {
    id: "simon",
    title: "Simon",
    thumbnailURL: "https://ultimateframedata.com/characterart/simon.jpg",
    ufPage: "https://ultimateframedata.com/simon.php",
  },
  {
    id: "snake",
    title: "Snake",
    thumbnailURL: "https://ultimateframedata.com/characterart/snake.jpg",
    ufPage: "https://ultimateframedata.com/snake.php",
  },
  {
    id: "sonic",
    title: "Sonic",
    thumbnailURL: "https://ultimateframedata.com/characterart/sonic.jpg",
    ufPage: "https://ultimateframedata.com/sonic.php",
  },
  {
    id: "steve",
    title: "Steve",
    thumbnailURL: "https://ultimateframedata.com/characterart/steve.jpg",
    ufPage: "https://ultimateframedata.com/steve.php",
  },
  {
    id: "sephiroth",
    title: "Sephiroth",
    thumbnailURL: "https://ultimateframedata.com/characterart/sephiroth.jpg",
    ufPage: "https://ultimateframedata.com/sephiroth.php",
  },
  {
    id: "terry",
    title: "Terry",
    thumbnailURL: "https://ultimateframedata.com/characterart/terry.jpg",
    ufPage: "https://ultimateframedata.com/terry.php",
  },
  {
    id: "toon_link",
    title: "Toon Link",
    thumbnailURL: "https://ultimateframedata.com/characterart/toon_link.jpg",
    ufPage: "https://ultimateframedata.com/toon_link.php",
  },
  {
    id: "villager",
    title: "Villager",
    thumbnailURL: "https://ultimateframedata.com/characterart/villager.jpg",
    ufPage: "https://ultimateframedata.com/villager.php",
  },
  {
    id: "wario",
    title: "Wario",
    thumbnailURL: "https://ultimateframedata.com/characterart/wario.jpg",
    ufPage: "https://ultimateframedata.com/wario.php",
  },
  {
    id: "wii_fit_trainer",
    title: "Wii Fit Trainer",
    thumbnailURL:
      "https://ultimateframedata.com/characterart/wii_fit_trainer.jpg",
    ufPage: "https://ultimateframedata.com/wii_fit_trainer.php",
  },
  {
    id: "wolf",
    title: "Wolf",
    thumbnailURL: "https://ultimateframedata.com/characterart/wolf.jpg",
    ufPage: "https://ultimateframedata.com/wolf.php",
  },
  {
    id: "yoshi",
    title: "Yoshi",
    thumbnailURL: "https://ultimateframedata.com/characterart/yoshi.jpg",
    ufPage: "https://ultimateframedata.com/yoshi.php",
  },
  {
    id: "young_link",
    title: "Young Link",
    thumbnailURL: "https://ultimateframedata.com/characterart/young_link.jpg",
    ufPage: "https://ultimateframedata.com/young_link.php",
  },
  {
    id: "zelda",
    title: "Zelda",
    thumbnailURL: "https://ultimateframedata.com/characterart/zelda.jpg",
    ufPage: "https://ultimateframedata.com/zelda.php",
  },
  {
    id: "zero_suit_samus",
    title: "Zero Suit Samus",
    thumbnailURL:
      "https://ultimateframedata.com/characterart/zero_suit_samus.jpg",
    ufPage: "https://ultimateframedata.com/zero_suit_samus.php",
  },
];

export default function handler(req, res) {
  res.status(200).json(chars);
}
